"""generate timestamp for workflow mapping

Revision ID: 0faf08436318
Revises: 8152695d2e7b
Create Date: 2025-04-08 16:30:29.537199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0faf08436318'
down_revision: Union[str, None] = '8152695d2e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_mappings',
                  sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True)
                  )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_mappings',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
                    sa.Column('workflow_id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('project_key', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('sprint_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='workflow_mappings_pkey')
                    )
    op.create_index('ix_workflow_mappings_workflow_id', 'workflow_mappings', ['workflow_id'], unique=True)
    op.create_index('ix_workflow_mappings_transaction_id', 'workflow_mappings', ['transaction_id'], unique=False)
    op.create_index('ix_workflow_mappings_sprint_id', 'workflow_mappings', ['sprint_id'], unique=False)
    op.create_index('ix_workflow_mappings_project_key', 'workflow_mappings', ['project_key'], unique=False)
    # ### end Alembic commands ###
