"""add author relationship

Revision ID: 24499e23a01e
Revises: 629dbe22cbab
Create Date: 2025-03-30 21:33:21.547286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24499e23a01e'
down_revision: Union[str, None] = '629dbe22cbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jira_issue_histories', 'author_id',
                    existing_type=sa.INTEGER(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=True)
    # op.drop_constraint('fk_jira_issues', 'jira_issue_histories', type_='foreignkey')
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    # op.drop_constraint('uq_jira_sprint_id', 'jira_sprints', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_jira_sprint_id', 'jira_sprints', ['jira_sprint_id'])
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    op.create_foreign_key('fk_jira_issues', 'jira_issue_histories', 'jira_issues', ['jira_issue_id'], ['jira_issue_id'])
    op.alter_column('jira_issue_histories', 'author_id',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    # ### end Alembic commands ###
