"""add project fk

Revision ID: 32c79a0ed6c9
Revises: 478e7c60f0c2
Create Date: 2025-03-20 04:08:07.281228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32c79a0ed6c9'
down_revision: Union[str, None] = '478e7c60f0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'jira_issues', 'projects', ['project_key'], ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jira_issues', type_='foreignkey')
    # ### end Alembic commands ###
