"""create deleted at for media

Revision ID: 342c29cdc48d
Revises: 59b148d59d07
Create Date: 2025-04-05 19:11:03.543602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '342c29cdc48d'
down_revision: Union[str, None] = '59b148d59d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('jira_users_uq_jira_account_id', 'jira_users', type_='unique')
    op.add_column('media', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'deleted_at')
    op.create_unique_constraint('jira_users_uq_jira_account_id', 'jira_users', ['jira_account_id'])
    # ### end Alembic commands ###
