"""add column for project table

Revision ID: 4b29b9c560a3
Revises: 32c79a0ed6c9
Create Date: 2025-03-20 04:12:28.788122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b29b9c560a3'
down_revision: Union[str, None] = '32c79a0ed6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projects', sa.Column('is_jira_linked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_jira_linked')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
