"""add user is_system_user

Revision ID: 4b92c0bcbc64
Revises: afa4fdb345f9
Create Date: 2025-03-05 23:56:17.335435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b92c0bcbc64'
down_revision: Union[str, None] = 'afa4fdb345f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_system_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_system_user')
    # ### end Alembic commands ###
