"""add is_deleted for jira sprints

Revision ID: 4beeb59556ae
Revises: 1201fb9340d5
Create Date: 2025-03-29 14:39:59.696486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4beeb59556ae'
down_revision: Union[str, None] = '1201fb9340d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    op.add_column('jira_sprints', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # op.drop_constraint('uq_jira_sprint_id', 'jira_sprints', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_jira_sprint_id', 'jira_sprints', ['jira_sprint_id'])
    op.drop_column('jira_sprints', 'is_deleted')
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    # ### end Alembic commands ###
