"""config project id field

Revision ID: 52eadade17dd
Revises: 141d39f830b8
Create Date: 2025-03-21 01:39:06.468494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52eadade17dd'
down_revision: Union[str, None] = '141d39f830b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jira_projects', 'project_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    op.alter_column('jira_projects', 'project_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
