"""generate manytomany sprint issue

Revision ID: 5a8f5f987d00
Revises: 1cc0499fa8ef
Create Date: 2025-03-21 13:43:42.492504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a8f5f987d00'
down_revision: Union[str, None] = '1cc0499fa8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jira_issues_sprint_id_fkey', 'jira_issues', type_='foreignkey')
    op.drop_column('jira_issues', 'sprint_id')
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    # op.drop_constraint('uq_jira_sprint_id', 'jira_sprints', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_jira_sprint_id', 'jira_sprints', ['jira_sprint_id'])
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    op.add_column('jira_issues', sa.Column('sprint_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('jira_issues_sprint_id_fkey', 'jira_issues',
                          'jira_sprints', ['sprint_id'], ['jira_sprint_id'])
    # ### end Alembic commands ###
