"""config story id

Revision ID: 5de66d0b48c9
Revises: 7e06c387943a
Create Date: 2025-05-04 21:35:08.088238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5de66d0b48c9'
down_revision: Union[str, None] = '7e06c387943a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_mappings_project_key', table_name='workflow_mappings')
    op.drop_index('ix_workflow_mappings_sprint_id', table_name='workflow_mappings')
    op.drop_index('ix_workflow_mappings_transaction_id', table_name='workflow_mappings')
    op.drop_index('ix_workflow_mappings_workflow_id', table_name='workflow_mappings')
    op.drop_table('workflow_mappings')
    op.create_unique_constraint('uq_jira_issue_history_jira_change_id_field_name', 'jira_issue_histories', ['jira_change_id', 'field_name'])
    op.drop_constraint('jira_issues_story_id_fkey', 'jira_issues', type_='foreignkey')
    op.create_foreign_key(None, 'jira_issues', 'jira_issues', ['story_id'], ['key'])
    op.drop_index('ix_system_configs_id', table_name='system_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_system_configs_id', 'system_configs', ['id'], unique=False)
    op.drop_constraint(None, 'jira_issues', type_='foreignkey')
    op.create_foreign_key('jira_issues_story_id_fkey', 'jira_issues', 'jira_issues', ['story_id'], ['jira_issue_id'])
    op.drop_constraint('uq_jira_issue_history_jira_change_id_field_name', 'jira_issue_histories', type_='unique')
    op.create_table('workflow_mappings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('workflow_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sprint_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_key'], ['jira_projects.key'], name='workflow_mappings_project_key_fkey'),
    sa.PrimaryKeyConstraint('id', name='workflow_mappings_pkey')
    )
    op.create_index('ix_workflow_mappings_workflow_id', 'workflow_mappings', ['workflow_id'], unique=True)
    op.create_index('ix_workflow_mappings_transaction_id', 'workflow_mappings', ['transaction_id'], unique=False)
    op.create_index('ix_workflow_mappings_sprint_id', 'workflow_mappings', ['sprint_id'], unique=False)
    op.create_index('ix_workflow_mappings_project_key', 'workflow_mappings', ['project_key'], unique=False)
    # ### end Alembic commands ###
