"""generate all tables

Revision ID: 5e0f967d5747
Revises: 
Create Date: 2025-04-05 14:11:46.974807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e0f967d5747'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_mappings_project_key', table_name='workflow_mappings')
    op.drop_index('ix_workflow_mappings_sprint_id', table_name='workflow_mappings')
    op.drop_index('ix_workflow_mappings_transaction_id', table_name='workflow_mappings')
    op.drop_index('ix_workflow_mappings_workflow_id', table_name='workflow_mappings')
    op.drop_table('workflow_mappings')
    op.alter_column('jira_issue_histories', 'field_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jira_issue_histories', 'old_value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('jira_issue_histories', 'new_value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('jira_issue_histories', 'old_string',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('jira_issue_histories', 'new_string',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_jira_issue_histories_author_id', table_name='jira_issue_histories')
    op.drop_index('ix_jira_issue_histories_created_at', table_name='jira_issue_histories')
    op.drop_index('ix_jira_issue_histories_field_name', table_name='jira_issue_histories')
    op.drop_index('ix_jira_issue_histories_jira_issue_id', table_name='jira_issue_histories')
    op.drop_constraint('jira_issue_histories_jira_change_id_key', 'jira_issue_histories', type_='unique')
    op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    op.drop_constraint('uq_jira_sprint_id', 'jira_sprints', type_='unique')
    op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    op.create_foreign_key(None, 'media', 'jira_users', ['uploaded_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_jira_sprint_id', 'jira_sprints', ['jira_sprint_id'])
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    op.create_unique_constraint('jira_issue_histories_jira_change_id_key', 'jira_issue_histories', ['jira_change_id'])
    op.create_index('ix_jira_issue_histories_jira_issue_id', 'jira_issue_histories', ['jira_issue_id'], unique=False)
    op.create_index('ix_jira_issue_histories_field_name', 'jira_issue_histories', ['field_name'], unique=False)
    op.create_index('ix_jira_issue_histories_created_at', 'jira_issue_histories', ['created_at'], unique=False)
    op.create_index('ix_jira_issue_histories_author_id', 'jira_issue_histories', ['author_id'], unique=False)
    op.alter_column('jira_issue_histories', 'new_string',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('jira_issue_histories', 'old_string',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('jira_issue_histories', 'new_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('jira_issue_histories', 'old_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('jira_issue_histories', 'field_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('workflow_mappings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sprint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_key'], ['jira_projects.key'], name='workflow_mappings_project_key_fkey'),
    sa.PrimaryKeyConstraint('id', name='workflow_mappings_pkey')
    )
    op.create_index('ix_workflow_mappings_workflow_id', 'workflow_mappings', ['workflow_id'], unique=True)
    op.create_index('ix_workflow_mappings_transaction_id', 'workflow_mappings', ['transaction_id'], unique=False)
    op.create_index('ix_workflow_mappings_sprint_id', 'workflow_mappings', ['sprint_id'], unique=False)
    op.create_index('ix_workflow_mappings_project_key', 'workflow_mappings', ['project_key'], unique=False)
    # ### end Alembic commands ###
