"""add jira_issue_history table

Revision ID: 629dbe22cbab
Revises: 4beeb59556ae
Create Date: 2025-03-30 21:22:10.833297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '629dbe22cbab'
down_revision: Union[str, None] = '4beeb59556ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_issue_histories', sa.Column('jira_issue_id',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_jira_issue_histories_issue_id', table_name='jira_issue_histories')
    op.create_index(op.f('ix_jira_issue_histories_jira_issue_id'),
                    'jira_issue_histories', ['jira_issue_id'], unique=False)
    op.create_foreign_key('fk_jira_issues', 'jira_issue_histories', 'jira_issues', ['jira_issue_id'], ['jira_issue_id'])
    op.drop_column('jira_issue_histories', 'issue_id')
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    # op.drop_constraint('uq_jira_sprint_id', 'jira_sprints', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_jira_sprint_id', 'jira_sprints', ['jira_sprint_id'])
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    op.add_column('jira_issue_histories', sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_jira_issue_histories_jira_issue_id'), table_name='jira_issue_histories')
    op.create_index('ix_jira_issue_histories_issue_id', 'jira_issue_histories', ['issue_id'], unique=False)
    op.drop_column('jira_issue_histories', 'jira_issue_id')
    # ### end Alembic commands ###
