"""config avatar, name for user field

Revision ID: 685acc491a92
Revises: 9085022809cc
Create Date: 2025-03-21 07:12:19.661286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '685acc491a92'
down_revision: Union[str, None] = '9085022809cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    op.add_column('jira_users', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jira_users', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.drop_column('jira_users', 'name')
    op.drop_column('jira_users', 'avatar_url')
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    # ### end Alembic commands ###
