"""addunique key

Revision ID: 7e06c387943a
Revises: 8b6b559bfb9a
Create Date: 2025-05-04 02:33:29.099337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e06c387943a'
down_revision: Union[str, None] = '8b6b559bfb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_workflow_mappings_project_key', table_name='workflow_mappings')
    # op.drop_index('ix_workflow_mappings_sprint_id', table_name='workflow_mappings')
    # op.drop_index('ix_workflow_mappings_transaction_id', table_name='workflow_mappings')
    # op.drop_index('ix_workflow_mappings_workflow_id', table_name='workflow_mappings')
    # op.drop_table('workflow_mappings')
    # op.alter_column('jira_issue_histories', 'jira_change_id',
    #                 existing_type=sa.VARCHAR(length=100),
    #                 nullable=False)
    # op.create_unique_constraint('uq_jira_issue_history_jira_change_id_field_name',
    #                             'jira_issue_histories', ['jira_change_id', 'field_name'])
    # op.drop_index('ix_jira_issue_sprints_id', table_name='jira_issue_sprints')
    # op.drop_column('jira_issue_sprints', 'id')
    # op.alter_column('jira_projects', 'created_at',
    #                 existing_type=postgresql.TIMESTAMP(),
    #                 type_=sa.DateTime(timezone=True),
    #                 nullable=True)
    # op.alter_column('jira_projects', 'updated_at',
    #                 existing_type=postgresql.TIMESTAMP(),
    #                 type_=sa.DateTime(timezone=True),
    #                 existing_nullable=True)
    # op.alter_column('jira_users', 'created_at',
    #                 existing_type=postgresql.TIMESTAMP(),
    #                 type_=sa.DateTime(timezone=True),
    #                 nullable=True)
    # op.alter_column('jira_users', 'updated_at',
    #                 existing_type=postgresql.TIMESTAMP(),
    #                 type_=sa.DateTime(timezone=True),
    #                 existing_nullable=True)
    # # op.drop_constraint('jira_users_uq_jira_account_id', 'jira_users', type_='unique')
    # op.alter_column('media', 'created_at',
    #                 existing_type=postgresql.TIMESTAMP(),
    #                 type_=sa.DateTime(timezone=True),
    #                 nullable=True)
    # op.alter_column('media', 'updated_at',
    #                 existing_type=postgresql.TIMESTAMP(),
    #                 type_=sa.DateTime(timezone=True),
    #                 existing_nullable=True)
    # op.alter_column('media', 'deleted_at',
    #                 existing_type=postgresql.TIMESTAMP(),
    #                 type_=sa.DateTime(timezone=True),
    #                 existing_nullable=True)
    # op.drop_index('ix_media_media_id', table_name='media')
    # op.create_index(op.f('ix_media_media_id'), 'media', ['media_id'], unique=True)
    # op.create_unique_constraint('uq_project_configs_project_system_config',
    #                             'project_configs', ['project_key', 'system_config_id'])
    # op.drop_constraint('project_configs_jira_projects_fk', 'project_configs', type_='foreignkey')
    # op.alter_column('refresh_tokens', 'created_at',
    #                 existing_type=postgresql.TIMESTAMP(),
    #                 type_=sa.DateTime(timezone=True),
    #                 nullable=True)
    # op.alter_column('sync_logs', 'created_at',
    #                 existing_type=postgresql.TIMESTAMP(),
    #                 type_=sa.DateTime(timezone=True),
    #                 nullable=True)
    # op.alter_column('sync_logs', 'updated_at',
    #                 existing_type=postgresql.TIMESTAMP(),
    #                 type_=sa.DateTime(timezone=True),
    #                 existing_nullable=True)
    # op.drop_index('ix_system_configs_id', table_name='system_configs')
    # op.drop_index('ix_system_configs_project_key', table_name='system_configs')
    # op.create_unique_constraint('uq_system_configs_key_scope', 'system_configs', ['key', 'scope'])
    # op.drop_column('system_configs', 'project_key')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_configs', sa.Column('project_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_system_configs_key_scope', 'system_configs', type_='unique')
    op.create_index('ix_system_configs_project_key', 'system_configs', ['project_key'], unique=False)
    op.create_index('ix_system_configs_id', 'system_configs', ['id'], unique=False)
    op.alter_column('sync_logs', 'updated_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('sync_logs', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    nullable=False)
    op.create_foreign_key('project_configs_jira_projects_fk', 'project_configs',
                          'jira_projects', ['project_key'], ['key'])
    op.drop_constraint('uq_project_configs_project_system_config', 'project_configs', type_='unique')
    op.drop_index(op.f('ix_media_media_id'), table_name='media')
    op.create_index('ix_media_media_id', 'media', ['media_id'], unique=False)
    op.alter_column('media', 'deleted_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('media', 'updated_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('media', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    nullable=False)
    op.create_unique_constraint('jira_users_uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.alter_column('jira_users', 'updated_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('jira_users', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('jira_projects', 'updated_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('jira_projects', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    nullable=False)
    op.add_column('jira_issue_sprints', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_jira_issue_sprints_id', 'jira_issue_sprints', ['id'], unique=False)
    op.drop_constraint('uq_jira_issue_history_jira_change_id_field_name', 'jira_issue_histories', type_='unique')
    op.alter_column('jira_issue_histories', 'jira_change_id',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)
    op.create_table('workflow_mappings',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('workflow_id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('project_key', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('sprint_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['project_key'], ['jira_projects.key'],
                                            name='workflow_mappings_project_key_fkey'),
                    sa.PrimaryKeyConstraint('id', name='workflow_mappings_pkey')
                    )
    op.create_index('ix_workflow_mappings_workflow_id', 'workflow_mappings', ['workflow_id'], unique=True)
    op.create_index('ix_workflow_mappings_transaction_id', 'workflow_mappings', ['transaction_id'], unique=False)
    op.create_index('ix_workflow_mappings_sprint_id', 'workflow_mappings', ['sprint_id'], unique=False)
    op.create_index('ix_workflow_mappings_project_key', 'workflow_mappings', ['project_key'], unique=False)
    # ### end Alembic commands ###
