"""generate all tables

Revision ID: 8152695d2e7b
Revises: 
Create Date: 2025-04-08 11:29:45.469352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8152695d2e7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('jira_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('is_system_user', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_jira_users_email'), 'jira_users', ['email'], unique=True)
    op.create_index(op.f('ix_jira_users_jira_account_id'), 'jira_users', ['jira_account_id'], unique=True)
    op.create_index(op.f('ix_jira_users_user_id'), 'jira_users', ['user_id'], unique=True)
    op.create_table('jira_projects',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('jira_project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('is_system_linked', sa.Boolean(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['jira_users.user_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_jira_projects_jira_project_id'), 'jira_projects', ['jira_project_id'], unique=True)
    op.create_index(op.f('ix_jira_projects_key'), 'jira_projects', ['key'], unique=True)
    op.create_index(op.f('ix_jira_projects_project_id'), 'jira_projects', ['project_id'], unique=True)
    op.create_index(op.f('ix_jira_projects_user_id'), 'jira_projects', ['user_id'], unique=False)
    op.create_table('media',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('media_id', sa.Uuid(), nullable=False),
                    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('blob_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('size', sa.Integer(), nullable=False),
                    sa.Column('uploaded_by', sa.Integer(), nullable=False),
                    sa.Column('container_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['uploaded_by'], ['jira_users.user_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_media_media_id'), 'media', ['media_id'], unique=True)
    op.create_table('refresh_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('token_type', sa.Enum('MICROSOFT', 'JIRA', name='tokentype'), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.Column('is_revoked', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['jira_users.user_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('sync_logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('request_payload', sa.JSON(), nullable=True),
                    sa.Column('response_status', sa.Integer(), nullable=True),
                    sa.Column('response_body', sa.JSON(), nullable=True),
                    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('sender', sa.Integer(), nullable=True),
                    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.CheckConstraint("entity_type IN ('ISSUE', 'PROJECT', 'SPRINT', 'USER')",
                                       name='valid_entity_type'),
                    sa.CheckConstraint("operation IN ('CREATE', 'UPDATE', 'DELETE', 'SYNC')", name='valid_operation'),
                    sa.CheckConstraint("source IN ('NATS', 'WEBHOOK', 'MANUAL')", name='valid_source'),
                    sa.ForeignKeyConstraint(['sender'], ['jira_users.user_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('jira_issues',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('jira_issue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('priority_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('estimate_point', sa.Float(), nullable=False),
                    sa.Column('actual_point', sa.Float(), nullable=True),
                    sa.Column('project_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('reporter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_locally', sa.Boolean(), nullable=False),
                    sa.Column('assignee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('is_system_linked', sa.Boolean(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['assignee_id'], ['jira_users.jira_account_id'], ),
                    sa.ForeignKeyConstraint(['project_key'], ['jira_projects.key'], ),
                    sa.ForeignKeyConstraint(['reporter_id'], ['jira_users.jira_account_id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('key')
                    )
    op.create_index(op.f('ix_jira_issues_jira_issue_id'), 'jira_issues', ['jira_issue_id'], unique=True)
    op.create_table('jira_sprints',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('jira_sprint_id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('complete_date', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('board_id', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.Column('project_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['project_key'], ['jira_projects.key'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_jira_sprints_jira_sprint_id'), 'jira_sprints', ['jira_sprint_id'], unique=True)
    op.create_table('jira_issue_histories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('jira_issue_id', sa.String(), nullable=False),
                    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
                    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
                    sa.Column('old_value', sa.Text(), nullable=True),
                    sa.Column('new_value', sa.Text(), nullable=True),
                    sa.Column('old_string', sa.Text(), nullable=True),
                    sa.Column('new_string', sa.Text(), nullable=True),
                    sa.Column('author_id', sa.String(), nullable=True),
                    sa.Column('jira_change_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['jira_users.jira_account_id'], name='fk_jira_users'),
                    sa.ForeignKeyConstraint(['jira_issue_id'], ['jira_issues.jira_issue_id'], name='fk_jira_issues'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('jira_issue_sprints',
                    sa.Column('jira_issue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('jira_sprint_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['jira_issue_id'], ['jira_issues.jira_issue_id'], ),
                    sa.ForeignKeyConstraint(['jira_sprint_id'], ['jira_sprints.jira_sprint_id'], ),
                    sa.PrimaryKeyConstraint('jira_issue_id', 'jira_sprint_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jira_issue_sprints')
    op.drop_table('jira_issue_histories')
    op.drop_index(op.f('ix_jira_sprints_jira_sprint_id'), table_name='jira_sprints')
    op.drop_table('jira_sprints')
    op.drop_index(op.f('ix_jira_issues_jira_issue_id'), table_name='jira_issues')
    op.drop_table('jira_issues')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_media_media_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_jira_projects_user_id'), table_name='jira_projects')
    op.drop_index(op.f('ix_jira_projects_project_id'), table_name='jira_projects')
    op.drop_index(op.f('ix_jira_projects_key'), table_name='jira_projects')
    op.drop_index(op.f('ix_jira_projects_jira_project_id'), table_name='jira_projects')
    op.drop_table('jira_projects')
    op.drop_index(op.f('ix_jira_users_user_id'), table_name='jira_users')
    op.drop_index(op.f('ix_jira_users_jira_account_id'), table_name='jira_users')
    op.drop_index(op.f('ix_jira_users_email'), table_name='jira_users')
    op.drop_table('jira_users')
    # ### end Alembic commands ###
