"""add board_id to jira sprints

Revision ID: 8c1d7d49ee3f
Revises: fb301ec1bab5
Create Date: 2025-03-28 03:52:05.559940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c1d7d49ee3f'
down_revision: Union[str, None] = 'fb301ec1bab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jira_issue_sprints', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    op.alter_column('jira_issues', 'last_synced_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    op.alter_column('jira_issues', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    op.alter_column('jira_issues', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    op.add_column('jira_sprints', sa.Column('board_id', sa.Integer(), nullable=True))
    op.alter_column('jira_sprints', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    # op.drop_constraint('uq_jira_sprint_id', 'jira_sprints', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_jira_sprint_id', 'jira_sprints', ['jira_sprint_id'])
    op.alter_column('jira_sprints', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    op.drop_column('jira_sprints', 'board_id')
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    op.alter_column('jira_issues', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    op.alter_column('jira_issues', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    op.alter_column('jira_issues', 'last_synced_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    op.alter_column('jira_issue_sprints', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    # ### end Alembic commands ###
