"""config user id field

Revision ID: 9085022809cc
Revises: 52eadade17dd
Create Date: 2025-03-21 02:03:59.384258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9085022809cc'
down_revision: Union[str, None] = '52eadade17dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    op.alter_column('jira_users', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.alter_column('jira_users', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    # ### end Alembic commands ###
