"""add user_id to project table

Revision ID: a42ae692287f
Revises: fd211b7a0d30
Create Date: 2025-03-22 21:34:42.699432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a42ae692287f'
down_revision: Union[str, None] = 'fd211b7a0d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_projects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_jira_projects_name', table_name='jira_projects')
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    op.create_index(op.f('ix_jira_projects_user_id'), 'jira_projects', ['user_id'], unique=False)
    op.create_foreign_key(None, 'jira_projects', 'jira_users', ['user_id'], ['user_id'])
    # op.drop_constraint('uq_jira_sprint_id', 'jira_sprints', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_jira_sprint_id', 'jira_sprints', ['jira_sprint_id'])
    op.drop_constraint(None, 'jira_projects', type_='foreignkey')
    op.drop_index(op.f('ix_jira_projects_user_id'), table_name='jira_projects')
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    op.create_index('ix_jira_projects_name', 'jira_projects', ['name'], unique=True)
    op.drop_column('jira_projects', 'user_id')
    # ### end Alembic commands ###
