"""generate is_system_linked

Revision ID: b86b74343927
Revises: 5a8f5f987d00
Create Date: 2025-03-21 16:17:43.647928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b86b74343927'
down_revision: Union[str, None] = '5a8f5f987d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_projects', sa.Column('is_system_linked', sa.Boolean(), nullable=False))
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    op.drop_column('jira_projects', 'is_jira_linked')
    # op.drop_constraint('uq_jira_sprint_id', 'jira_sprints', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_jira_sprint_id', 'jira_sprints', ['jira_sprint_id'])
    op.add_column('jira_projects', sa.Column('is_jira_linked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    op.drop_column('jira_projects', 'is_system_linked')
    # ### end Alembic commands ###
