"""generate needed relations

Revision ID: d2df6516092a
Revises: 24499e23a01e
Create Date: 2025-03-30 23:22:17.716934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2df6516092a'
down_revision: Union[str, None] = '24499e23a01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('fk_jira_issues', 'jira_issue_histories', type_='foreignkey')
    # op.drop_constraint('fk_jira_users', 'jira_issue_histories', type_='foreignkey')
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    # op.drop_constraint('uq_jira_sprint_id', 'jira_sprints', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_jira_sprint_id', 'jira_sprints', ['jira_sprint_id'])
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    op.create_foreign_key('fk_jira_users', 'jira_issue_histories', 'jira_users', ['author_id'], ['jira_account_id'])
    op.create_foreign_key('fk_jira_issues', 'jira_issue_histories', 'jira_issues', ['jira_issue_id'], ['jira_issue_id'])
    # ### end Alembic commands ###
