"""generate sync log table

Revision ID: d446baa8a137
Revises: 9ff69d2d9e1c
Create Date: 2025-03-20 22:21:39.256378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd446baa8a137'
down_revision: Union[str, None] = '9ff69d2d9e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    # ### end Alembic commands ###
