"""remove is_jira_linked

Revision ID: f846fb276c15
Revises: a16ebb783d2b
Create Date: 2025-02-24 02:20:37.681431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f846fb276c15'
down_revision: Union[str, None] = 'a16ebb783d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_jira_linked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_jira_linked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
