"""add is_deleted and link_url to jira issue table

Revision ID: fb301ec1bab5
Revises: a42ae692287f
Create Date: 2025-03-23 19:57:20.110727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb301ec1bab5'
down_revision: Union[str, None] = 'a42ae692287f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_issues', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('jira_issues', sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.drop_constraint('uq_project_key', 'jira_projects', type_='unique')
    # op.drop_constraint('uq_jira_sprint_id', 'jira_sprints', type_='unique')
    # op.drop_constraint('uq_jira_account_id', 'jira_users', type_='unique')
    # op.drop_constraint('uq_user_id', 'jira_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id', 'jira_users', ['user_id'])
    op.create_unique_constraint('uq_jira_account_id', 'jira_users', ['jira_account_id'])
    op.create_unique_constraint('uq_jira_sprint_id', 'jira_sprints', ['jira_sprint_id'])
    op.create_unique_constraint('uq_project_key', 'jira_projects', ['key'])
    op.drop_column('jira_issues', 'link_url')
    op.drop_column('jira_issues', 'is_deleted')
    # ### end Alembic commands ###
